// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYg-C0wMImjQzJ_Tlz7YOoq-HYETOcCOc',
    appId: '1:91788469204:web:27f47e46eab0317bf6ac41',
    messagingSenderId: '91788469204',
    projectId: 'car-rental-app-se',
    authDomain: 'car-rental-app-se.firebaseapp.com',
    storageBucket: 'car-rental-app-se.appspot.com',
    measurementId: 'G-HMV55CGEVX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5z1kr-fnHLcDn-O9AWro6VwW0G-PS3V0',
    appId: '1:91788469204:android:fc69306be1f40680f6ac41',
    messagingSenderId: '91788469204',
    projectId: 'car-rental-app-se',
    storageBucket: 'car-rental-app-se.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsy51F3trct1ieAe5sQn96Tf0ikQeNVjc',
    appId: '1:91788469204:ios:8aec440547469478f6ac41',
    messagingSenderId: '91788469204',
    projectId: 'car-rental-app-se',
    storageBucket: 'car-rental-app-se.appspot.com',
    iosClientId: '91788469204-n6flja41cef50dmursprumls1ovavo4s.apps.googleusercontent.com',
    iosBundleId: 'com.example.rentalapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBsy51F3trct1ieAe5sQn96Tf0ikQeNVjc',
    appId: '1:91788469204:ios:8aec440547469478f6ac41',
    messagingSenderId: '91788469204',
    projectId: 'car-rental-app-se',
    storageBucket: 'car-rental-app-se.appspot.com',
    iosClientId: '91788469204-n6flja41cef50dmursprumls1ovavo4s.apps.googleusercontent.com',
    iosBundleId: 'com.example.rentalapp',
  );
}
